"""Constants for CLI module."""

# Display constants
MAX_FILENAME_DISPLAY_LENGTH = 37
FILENAME_TRUNCATE_LENGTH = 34

# Time constants (in seconds)
MAX_REASONABLE_RESPONSE_TIME = 3600  # 1 hour
MIN_CHAIN_DEPTH_FOR_CONCLUSION = 2
DEFAULT_CHECK_INTERVAL = 5
DEFAULT_PARALLEL_WORKERS = 4

# Analysis thresholds
MIN_MESSAGES_FOR_PATTERN_ANALYSIS = 10
HIGH_IMPORTANCE_THRESHOLD = 70
MEDIUM_IMPORTANCE_THRESHOLD = 30
LOW_IMPORTANCE_THRESHOLD = 20

# Monitoring constants
DEFAULT_MONITOR_DIRECTORY = "~/.claude/projects"
DEFAULT_OUTPUT_FILE = "conversation_changes.txt"
DEFAULT_FILE_PATTERN = "*.jsonl"
MONITORING_STATE_FILE = ".ccmonitor_state.pkl"

# Performance thresholds
MAX_PROCESSING_TIME_WARNING = 10.0  # seconds
MAX_FILE_SIZE_WARNING = 100_000_000  # 100MB

# Analysis constants
MIN_MESSAGES_FOR_ANALYSIS = 2
SYSTEM_RATIO_THRESHOLD = 0.3
REPETITIVE_CONTENT_THRESHOLD = 0.4
AGGRESSIVE_REDUCTION_FACTOR = 0.6
MODERATE_REDUCTION_FACTOR = 0.4
CONSERVATIVE_REDUCTION_FACTOR = 0.2
HIGH_CONFIDENCE_THRESHOLD = 0.8
MODERATE_CONFIDENCE_THRESHOLD = 0.6
LARGE_MESSAGE_COUNT = 100
HOURLY_GAP_THRESHOLD = 1  # hours
DAILY_ACTIVITY_THRESHOLD = 10  # messages per day

# Reporting analysis thresholds
VERBOSE_CONTENT_THRESHOLD = 0.5
IMPORTANT_CONTENT_RATIO_THRESHOLD = 0.7
DEPENDENCY_COMPLEXITY_THRESHOLD = 0.7
HIGH_IMPORTANT_CONTENT_THRESHOLD = 0.8
SMALL_CONVERSATION_SIZE_THRESHOLD = 50
LARGE_CONVERSATION_CONFIDENCE_THRESHOLD = 100

# Trend analysis constants
MIN_TIMESTAMPS_FOR_TREND = 10
MIN_HOURLY_COUNTS_FOR_TREND = 3
MIN_VALUES_FOR_TREND = 3
TREND_SLOPE_INCREASE_THRESHOLD = 0.1
TREND_SLOPE_DECREASE_THRESHOLD = -0.1

# Frequency trend multipliers
INCREASING_TREND_MULTIPLIER = 1.2
DECREASING_TREND_MULTIPLIER = 0.8

# Topic analysis constants
MIN_CONTENTS_FOR_TOPIC_PROGRESSION = 5
FOCUSED_TOPIC_OVERLAP_THRESHOLD = 0.7
SCATTERED_TOPIC_OVERLAP_THRESHOLD = 0.3
MIN_KEYWORD_LENGTH = 3

# Content analysis thresholds
VERBOSE_CONTENT_LENGTH_THRESHOLD = 2000
VERBOSE_CODE_BLOCK_THRESHOLD = 2
VERBOSE_SYSTEM_MESSAGE_THRESHOLD = 500
IMPORTANT_ASSISTANT_MESSAGE_THRESHOLD = 200
HIGH_ACTIVITY_MESSAGES_PER_DAY = 50

# Score distribution thresholds
SCORE_HIGH_THRESHOLD = 60
SCORE_MEDIUM_THRESHOLD = 30

# Statistical analysis thresholds
HIGH_DIVERSITY_CV_THRESHOLD = 0.5  # Coefficient of variation for high diversity
MEDIUM_DIVERSITY_CV_THRESHOLD = 0.2  # Coefficient of variation for medium diversity

# System constants
BYTES_PER_KILOBYTE = 1024  # Standard binary byte conversion
SECONDS_PER_MINUTE = 60  # Time conversion
SECONDS_PER_HOUR = 3600  # Time conversion

# File format detection
JSONL_DETECTION_SAMPLE_LINES = 3  # Number of lines to check for JSONL format
