"""Constants for JSONL analysis module."""

# Scoring weights
DEFAULT_CODE_CHANGES_WEIGHT = 40
DEFAULT_ERROR_SOLUTION_WEIGHT = 35
DEFAULT_ARCHITECTURAL_DECISION_WEIGHT = 30
DEFAULT_USER_QUESTION_WEIGHT = 20
DEFAULT_FILE_MODIFICATION_WEIGHT = 25
DEFAULT_DEBUGGING_INFO_WEIGHT = 15
HOOK_LOG_PENALTY = -30
SYSTEM_VALIDATION_PENALTY = -25
EMPTY_OUTPUT_PENALTY = -20
CONVERSATION_ROOT_BOOST = 15
CONVERSATION_CHAIN_BOOST = 10
CONVERSATION_CONCLUSION_BOOST = 8

# Dependency scoring
HAS_CHILDREN_BOOST = 12
IS_ROOT_BOOST = 10
CHAIN_LENGTH_MULTIPLIER = 2
RECENT_CHILD_BONUS = 15
RECENT_CHILD_DAYS_THRESHOLD = 7

# Tool scoring
WRITE_TOOL_SCORE = 40
EDIT_TOOL_SCORE = 40
MULTIEDIT_TOOL_SCORE = 40
READ_TOOL_SCORE = 20
GLOB_TOOL_SCORE = 15
GREP_TOOL_SCORE = 20
BASH_TOOL_SCORE = 25
TODO_WRITE_SCORE = 5
DEFAULT_TOOL_SCORE = 10

# Analysis thresholds
RESULT_TRUNCATE_LENGTH = 500
MIN_CHAIN_DEPTH_FOR_CONCLUSION = 2
ERROR_CONFIDENCE_BOOST = 0.3
HOOK_CONFIDENCE_BOOST = 0.4

# Pattern detection
MIN_RECURRING_ERROR_COUNT = 3
MAX_DEPENDENCY_CHAIN_BONUS = 20

# Score ranges
MAX_IMPORTANCE_SCORE = 100.0
MIN_IMPORTANCE_SCORE = 0.0
HIGH_VALUE_THRESHOLD = 70
LOW_VALUE_THRESHOLD = 20

# Sequence analysis constants
# Messages within this distance are considered a sequence
TOOL_SEQUENCE_PROXIMITY_THRESHOLD = 5
