"""Constants for utils module."""

# Importance scoring thresholds
HIGH_SCORE_THRESHOLD = 70
MEDIUM_SCORE_THRESHOLD = 30
LOW_SCORE_THRESHOLD = 20

# Conversation analysis
MIN_SUBSTANTIAL_CHAIN_DEPTH = 2
MAX_CHAIN_BONUS = 20
RECENT_CHILD_DAYS_THRESHOLD = 7
ERROR_SOLUTION_SEARCH_WINDOW = 4
TOOL_SEQUENCE_MAX_GAP = 5

# Performance monitoring
PERFORMANCE_TREND_DAYS = 30
OPERATION_TIMEOUT_SECONDS = 30.0
MIN_OPERATIONS_FOR_TREND = 10
PERFORMANCE_CACHE_SIZE = 1000

# Quality metrics
QUALITY_SCORE_EXCELLENT = 90
QUALITY_SCORE_GOOD = 70
QUALITY_SCORE_FAIR = 50
QUALITY_SCORE_POOR = 30

# Alert thresholds
HIGH_SEVERITY_MULTIPLIER = 1.5
ALERT_HISTORY_LIMIT = 1000
ERROR_HISTORY_LIMIT = 1000

# Validation
MIN_COMPRESSION_RATIO = 0.1
MAX_COMPRESSION_RATIO = 0.95
MAX_FALSE_POSITIVE_RATE = 0.05
MIN_PROCESSING_SPEED = 100  # messages/second

# File handling
DEFAULT_LINE_LIMIT = 2000
MAX_LINE_LENGTH = 2000
DEFAULT_JSON_INDENT = 2

# Quality rating thresholds
EXCELLENT_QUALITY_THRESHOLD = 0.9
GOOD_QUALITY_THRESHOLD = 0.8
ACCEPTABLE_QUALITY_THRESHOLD = 0.7
NEEDS_IMPROVEMENT_QUALITY_THRESHOLD = 0.6

# Analysis constants
MIN_RECENT_SCORES_FOR_TREND = 2
CRITICAL_ERROR_THRESHOLD = 3
TREND_ANALYSIS_DAYS = 7
MIN_METRICS_FOR_TREND_ANALYSIS = 10
RECURRING_ERROR_THRESHOLD = 3

# Quality assurance thresholds
FALSE_POSITIVE_RATE_THRESHOLD = 0.01  # Maximum acceptable false positive rate (1%)
MINIMUM_QUALITY_SCORE = 0.8  # Minimum quality score for passing validation
PERFORMANCE_TIME_LIMIT = 5.0  # Maximum acceptable total validation time (seconds)
SLOW_LEVEL_THRESHOLD = 2.0  # Threshold for identifying slow validation levels
