environment: production
host: "0.0.0.0"
port: 8000
workers: 8
max_agents: 20
database_url: "PRPs/production.db"
redis_url: "redis://localhost:6379"
log_level: "INFO"
cors_origins:
  - "https://yourapp.com"
  - "https://api.yourapp.com"
api_key_required: true
model_versioning: true
auto_scaling: true
health_check_interval: 30
metrics_retention_days: 90
backup_enabled: true
backup_interval_hours: 6